# -*- coding: utf-8 -*-
"""Aula 3 — A lava que sobe."""

AULA = {
 "n": 3,
 "slug": "aula3",
 "titulo": "A lava que sobe",
 "subtitulo": "A lava não fica mais parada: ela sobe sozinha. Suba a escada de plataformas e pegue a estrela antes que ela chegue.",
 "tempo": "50 minutos",
 "etiqueta": "Aula 3 · corrida contra a lava",
 "fim": "Acabou a Aula 3. Hoje você fez a primeira coisa que se mexe <b>sem ninguém apertar tecla nenhuma</b> — e isso é metade de todo jogo que existe. Mande o link do seu jogo para a sua família tentar chegar na estrela.",
 "avisos": [
   ("Jogo novo", "Esta aula começa num jogo novo, do zero. Os das aulas 1 e 2 ficam guardados na sua lista."),
   ("O que é novo hoje", "Uma coisa que <b>anda sozinha</b>: a lava. Três blocos fazem isso — <span class=ui>Always</span>, <span class=ui>Number</span> e <span class=ui>Velocity</span>."),
   ("Os clipes", "Os passos com animação mostram o gesto inteiro: o mouse andando, o <b>botão certo acendendo</b> e o que muda na tela."),
   ("Travou?", "Todo passo tem um quadro laranja embaixo com o conserto dos erros mais comuns."),
 ],
 "passos": [

  dict(n=1, titulo="Abra o Flowlab e entre em MY GAMES", img="comum_fotos/c02_lista.jpg", clipe="abrir_my_games.gif",
    corpo="No navegador, vá para <span class=ui>flowlab.io</span>.<br><br>Se aparecer <span class=ui>Log in</span> no canto de cima à direita, clique nele e entre com a sua conta — sem entrar, o jogo não fica salvo.<br><br>Depois, no alto à direita, clique em <span class=ui>My Games</span>. Os jogos das aulas 1 e 2 estão aí na lista, guardados. Hoje a gente faz outro, do zero.",
    ck="O título da página é <span class=ui>My Games</span> e os seus jogos anteriores aparecem na lista.",
    sos=[("Aparece Log in","Clique nele e entre com o e-mail e a senha da sua conta."),
         ("Minha lista está vazia","Você pode estar em outra conta. Clique na bolinha do canto de cima e confira.")]),

  dict(n=2, titulo="Crie um jogo novo", img="comum_fotos/c03_escolher.jpg", clipe="novo_jogo.gif",
    corpo="Clique no botão verde <span class=ui>+ New Game</span>, no canto direito.",
    ck="Apareceram duas figuras: <span class=ui>Empty Project</span> e <span class=ui>Flowlab Tutorial</span>.",
    sos=[("Não aconteceu nada","Clique de novo, uma vez só, bem no meio do botão verde. Às vezes ele demora alguns segundos para abrir a janelinha.")]),

  dict(n=3, titulo="Escolha o PROJETO VAZIO", img="aula3/p01_vazio.jpg", clipe="empty_project.gif",
    corpo="Clique na <b>figura</b> da esquerda, a do <b>+</b> grande.<br><br>Clique na figura, não no nome embaixo dela — o nome não responde.",
    ck="Sobrou a folha branca vazia, com a fileira <span class=ui>Play · Library · Game Levels · Layer · Settings</span> embaixo.",
    sos=[("Abriu o Flowlab Tutorial","Volte para <span class=ui>My Games</span>, apague esse jogo nos três pontinhos e comece de novo.")]),

  dict(n=4, titulo="Crie o jogador", img="aula3/g01_b.jpg", clipe="criar_objeto.gif",
    corpo="Clique uma vez dentro da folha branca, na <b>parte de baixo e à esquerda</b> — o boneco vai começar ali, e a escada vai subir para a direita.<br><br>Abre a roda com <span class=ui>Create</span> e <span class=ui>Cancel</span>.",
    ck="Apareceu a roda escura com <span class=ui>Create</span> e <span class=ui>Cancel</span>.",
    sos=[("Apareceu Clone, Edit, Delete","Aquela casa já tem um objeto. Clique em <span class=ui>Cancel</span> e escolha uma casa vazia.")]),

  dict(n=5, titulo="Escolha CREATE", img="aula3/g02_b.jpg", clipe="escolher_create.gif",
    corpo="Na roda, clique em <span class=ui>Create</span>, em cima à direita.<br><br>Abre o painel do objeto novo, com <span class=ui>edit sprite</span> à esquerda e os campos <span class=ui>Type</span> e <span class=ui>Name</span>.",
    ck="O painel do objeto está aberto e mostra <span class=ui>edit sprite</span>, <span class=ui>Type</span>, <span class=ui>Name</span> e <span class=ui>Behaviors</span>.",
    sos=[("Fechou tudo","Você clicou em <span class=ui>Cancel</span>. Clique de novo na casa e escolha <span class=ui>Create</span>."),
         ("A roda sumiu sozinha","Clique de novo na mesma casa — ela ainda está vazia.")]),

  dict(n=6, titulo="Escreva JOGADOR nos DOIS campos", img="aula3/p02_nome.jpg", clipe=None,
    corpo="No painel há dois campos lado a lado:<br><br><b>1.</b> Em <span class=ui>Name</span>, apague o que estiver escrito e escreva <b>Jogador</b>.<br><b>2.</b> Em <span class=ui>Type</span>, à esquerda do Name, apague e escreva <b>Jogador</b> também.<br><br>Aperte <b>Tab</b> depois de cada um (o Enter fecha o painel).<br><br>Por que os dois: o <span class=ui>Name</span> é o apelido do objeto, e serve para você. O <span class=ui>Type</span> é o que <b>os outros objetos enxergam</b> — mais para a frente a lava vai precisar dizer “eu só conto quando bater no Jogador”, e o nome que ela vai procurar na lista é o do <span class=ui>Type</span>.",
    ck="<span class=ui>Type</span> e <span class=ui>Name</span> mostram os dois a palavra <b>Jogador</b>.",
    sos=[("O painel fechou quando eu apertei Enter","Normal. Clique de novo na casa do boneco, escolha <span class=ui>Edit</span> e confira os dois campos."),
         ("Só consegui mudar um","Clique duas vezes dentro do campo que faltou, apague tudo e escreva de novo."),
         ("Escrevi errado e já fechou","Dá para voltar: clique na casa, escolha <span class=ui>Edit</span> e corrija.")]),

  dict(n=7, titulo="Pinte o jogador de azul", img="aula3/p03_azul.jpg", clipe=None,
    corpo="Clique em <span class=ui>edit sprite</span>, o quadradinho à esquerda do painel.<br><br>Abre a tela de desenho. Clique na <b>latinha de tinta</b> (a terceira ferramenta da fileira de cima), depois no <b>azul</b> da paleta à direita, e então <b>dentro do quadrado grande</b> do meio.<br><br>Para fechar, clique em <span class=ui>OK</span>, no canto de baixo à esquerda.",
    ck="O quadradinho do <span class=ui>edit sprite</span> ficou azul, e o boneco na folha branca também.",
    sos=[("Pintei e só mudou um pedacinho","A latinha pinta a área que você clicou. Clique em outro canto do quadrado grande até ele ficar todo azul."),
         ("Não acho a latinha","É a terceira ferramenta da primeira fileira, com a tinta escorrendo.")]),

  dict(n=8, titulo="Abra a física e marque MOVABLE", img="aula3/g04_b.jpg", clipe="marcar_movable.gif",
    corpo="No painel do objeto, clique em <span class=ui>Physics &gt;</span>, no canto de baixo à direita.<br><br>O painel troca e mostra as caixinhas da física. Clique na <b>caixinha</b> de <span class=ui>movable</span> — bem no quadradinho, não na palavra.<br><br><span class=ui>movable</span> quer dizer <i>pode se mexer</i>. Sem ela, o boneco fica pregado no lugar e nenhum comando faz ele andar.",
    ck="A caixinha <span class=ui>movable</span> ficou <b>azul</b>, e apareceu <span class=ui>affected by gravity</span> ao lado, também marcada.",
    sos=[("Não acho o Physics","Ele fica no canto de baixo à direita do painel do objeto, escrito pequeno."),
         ("A caixinha não fica azul","Clique bem em cima do quadradinho, não na palavra."),
         ("Density está cinza","Ela só liga depois que <span class=ui>movable</span> estiver marcado.")]),

  dict(n=9, titulo="Dê o peso certo ao jogador", img="aula3/p04_fisica.jpg", clipe="peso_do_pulo.gif",
    corpo="Ainda na física, mexa em dois controles:<br><br><b>1.</b> Em <span class=ui>Density</span> (peso), clique na barrinha <b>um pouco antes da metade</b>, até o número ao lado ficar perto de <b>30</b>. A barrinha marca o valor <b>onde você clica</b>: se passar de 30, clique um pouco mais para a <b>esquerda</b>; se ficar abaixo, um pouco mais para a <b>direita</b>.<br><b>2.</b> Em <span class=ui>Friction</span> (atrito), clique na <b>ponta direita</b> da barrinha, para ficar <b>100</b>.<br><br>O pulo do Flowlab tem força <b>fixa</b>. Pesado demais, ela não levanta o boneco do chão e ele simplesmente não pula. Leve demais, ele sai voando para fora da tela. Perto de <b>30</b> ele pula a altura de umas quatro casas — que é exatamente o degrau desta fase.",
    ck="<span class=ui>Density</span> mostra um número perto de <b>30</b> e <span class=ui>Friction</span> mostra <b>100.0</b>.",
    sos=[("O número foi para 100 e eu queria 30","Você clicou perto da ponta direita. Clique de novo um pouco antes da metade da barrinha."),
         ("O número foi para 3","Você clicou na ponta esquerda. Clique um pouco mais para a direita."),
         ("Density está cinza e não muda","Volte ao passo 8: ele só funciona com <span class=ui>movable</span> marcado.")]),

  dict(n=10, titulo="Dê movimento e pulo ao jogador", img="aula3/p05_run_and_jump.jpg", clipe=None,
    corpo="Feche a física no <span class=ui>OK</span> azul e, no painel do objeto, clique em <span class=ui>Behaviors</span>.<br><br>Abre a mesa de blocos. Na coluna da esquerda, lá embaixo, clique em <span class=ui>Behavior Bundles</span> e <b>arraste</b> <span class=ui>Run &amp; Jump</span> para o meio da mesa.<br><br>Esse pacote já vem pronto: é ele que faz o boneco <b>correr com as setas</b> e <b>pular</b>.<br><br>Para sair da mesa de blocos, clique no <span class=ui>OK</span> azul do canto de baixo à esquerda; depois feche o painel do objeto no <span class=ui>OK</span> azul dele.",
    ck="Um bloco escrito <span class=ui>Run &amp; Jump</span> está na mesa, e você voltou a ver a folha branca com o boneco.",
    sos=[("Arrastei e não ficou nada","Puxe de novo, mais devagar, e solte no meio da área escura."),
         ("Não acho Behavior Bundles","É a última linha da coluna da esquerda. Clique nela para abrir a lista."),
         ("Fiquei preso na mesa de blocos","São dois OK azuis, um depois do outro: o da mesa e o do painel do objeto.")]),

  dict(n=11, titulo="Faça o chão", img="aula3/p06_chao.jpg", clipe=None,
    corpo="Clique numa casa vazia <b>uma fileira abaixo do boneco e duas casas à esquerda</b> dele, e escolha <span class=ui>Create</span>.<br><br>Em <span class=ui>Name</span>, escreva <b>Chao</b>. Clique em <span class=ui>edit sprite</span>, pinte de <b>verde</b> e feche no <span class=ui>OK</span>.<br><br>Agora repita essa peça para o lado: clique na casa dela, escolha <span class=ui>Clone</span> e clique nas <b>cinco casas seguintes à direita</b>, uma de cada vez. Para terminar, clique em <span class=ui>done cloning</span>.",
    ck="Uma faixa verde de <b>seis casas</b> começa embaixo do boneco e segue para a direita.",
    sos=[("As peças ficaram com buraco no meio","Clique exatamente na casa vizinha, sem pular nenhuma. Buraco no chão derruba o boneco."),
         ("Cliquei e não colocou","No modo clone o clique precisa ser mais devagar. Vá uma casa por vez."),
         ("Saí do clone sem querer","Clique na peça de novo, escolha <span class=ui>Clone</span> e continue de onde parou.")]),

  dict(n=12, titulo="Faça o segundo degrau", img="aula3/p07_plataforma.jpg", clipe=None,
    corpo="Clique numa casa vazia <b>duas fileiras acima do chão</b> e <b>uma coluna à direita</b> de onde o chão termina, e escolha <span class=ui>Create</span>.<br><br>Em <span class=ui>Name</span>, escreva <b>Plataforma</b>. Clique em <span class=ui>edit sprite</span>, pinte de <b>verde</b> e feche no <span class=ui>OK</span>.<br><br>Depois clone essa peça para as <b>quatro casas seguintes à direita</b> e clique em <span class=ui>done cloning</span>.",
    ck="Um segundo degrau verde, de <b>cinco casas</b>, está mais alto e mais à direita que o chão.",
    sos=[("O degrau ficou alto demais","Duas fileiras acima do chão, não mais. Mais alto que isso o boneco não alcança no pulo."),
         ("O degrau ficou colado no chão","Deixe uma coluna de distância para a direita, senão não há vão nenhum para pular.")]),

  dict(n=13, titulo="Faça o terceiro degrau", img="aula3/p08_tres_plataformas.jpg", clipe=None,
    corpo="Mais uma vez: clique numa casa vazia <b>duas fileiras acima do segundo degrau</b> e <b>uma coluna à direita</b> de onde ele termina, e escolha <span class=ui>Create</span>.<br><br>Em <span class=ui>Name</span>, escreva <b>Alta</b>. Clique em <span class=ui>edit sprite</span>, pinte de <b>verde</b> e feche no <span class=ui>OK</span>.<br><br>Clone para as <b>três casas seguintes à direita</b>, até encostar na beirada da folha, e clique em <span class=ui>done cloning</span>.",
    ck="Agora são <b>três degraus verdes</b> subindo da esquerda para a direita, como uma escada.",
    sos=[("Não cabe até a beirada","Tudo bem terminar uma casa antes. O que importa é o degrau ser largo."),
         ("Pulei uma fileira a mais","Clique na peça errada, escolha <span class=ui>Delete</span> e refaça duas fileiras acima.")]),

  dict(n=14, titulo="Ponha a lava no pé da tela", img="aula3/p09_lava.jpg", clipe=None,
    corpo="Clique na <b>casa do canto de baixo à esquerda</b> da folha branca e escolha <span class=ui>Create</span>.<br><br>Em <span class=ui>Name</span>, escreva <b>Lava</b>. Clique em <span class=ui>edit sprite</span>, pinte de <b>vermelho</b> e feche no <span class=ui>OK</span>.<br><br>Agora clone a lava por <b>toda a fileira de baixo</b>, de ponta a ponta, sem deixar buraco, e clique em <span class=ui>done cloning</span>.",
    ck="Uma faixa vermelha atravessa a tela inteira na fileira de baixo, de uma beirada à outra.",
    sos=[("Sobrou um buraco na ponta","Tape: a lava precisa cobrir tudo, senão o boneco cai pelo vão e o jogo fica travado."),
         ("A lava ficou em cima do chão verde","Ela vai na <b>última</b> fileira, a mais baixa de todas. Apague e refaça embaixo.")]),

  dict(n=15, titulo="Ensine a lava a se mexer", img="aula3/p10_lava_sem_gravidade.jpg", clipe="lava_sente_o_toque.gif",
    corpo="Clique na <b>primeira peça da lava</b>, escolha <span class=ui>Edit</span> e depois <span class=ui>Physics &gt;</span>.<br><br>Mexa em <b>quatro</b> caixinhas, nesta ordem:<br><br><b>1.</b> <span class=ui>movable</span> — <b>marque</b>. Sem isso ela fica pregada.<br><b>2.</b> <span class=ui>affected by gravity</span> — <b>desmarque</b>. Com gravidade ela cai, e a gente quer que suba.<br><b>3.</b> <span class=ui>is solid</span> — <b>desmarque</b>. Assim a lava <b>atravessa</b> os degraus em vez de ficar entalada embaixo deles.<br><b>4.</b> <span class=ui>enable collisions</span> — apareceu agora no lugar do <span class=ui>is solid</span>. <b>Marque</b>. Ela devolve o <i>toque</i> sem devolver o <i>empurrão</i>.<br><br>Os dois últimos andam juntos: sem o 3 a lava sobe e trava nos degraus; sem o 4 ela sobe por cima do boneco e <b>não acontece nada</b>.<br><br>Feche no <span class=ui>OK</span> azul.",
    ck="<span class=ui>movable</span> e <span class=ui>enable collisions</span> estão azuis; <span class=ui>affected by gravity</span> e <span class=ui>is solid</span> estão apagados.",
    sos=[("Não existe enable collisions no meu painel","Ela só nasce depois que <span class=ui>is solid</span> for desmarcado. Faça o 3 primeiro."),
         ("Marquei na palavra e não mudou","A caixinha é o quadradinho à esquerda da palavra. Clique nele."),
         ("Mexi na peça errada","Qualquer peça da lava serve: elas são todas o mesmo objeto, e o que você mudar vale para todas.")]),

  dict(n=16, titulo="Monte os três blocos da lava", img="aula3/p14_fios.jpg", clipe=None,
    corpo="Com a lava ainda aberta, clique em <span class=ui>Behaviors</span>. Abre a mesa de blocos dela, vazia.<br><br>Arraste três blocos da coluna da esquerda:<br><br><b>1.</b> Em <span class=ui>Triggers</span>, o <span class=ui>Always</span> — solte na parte de cima da mesa.<br><b>2.</b> Em <span class=ui>Logic &amp; Math</span>, o <span class=ui>Number</span> — solte no meio, mais abaixo.<br><b>3.</b> Em <span class=ui>Properties</span>, o <span class=ui>Velocity</span> — solte à direita, na altura do Always.<br><br>Agora os fios. Arraste de <b>bolinha a bolinha</b>, devagar:<br><br><b>4.</b> Da bolinha <span class=ui>out</span> do <span class=ui>Always</span> até a bolinha <span class=ui>get</span> do <span class=ui>Number</span>.<br><b>5.</b> Da bolinha <span class=ui>out</span> do <span class=ui>Number</span> até a bolinha <span class=ui>y</span> do <span class=ui>Velocity</span>.<br><br>Lendo em voz alta: <i>sempre</i> (Always) pegue <i>este número</i> (Number) e use como <i>velocidade para cima e para baixo</i> (y).",
    ck="Três blocos na mesa e <b>dois fios brancos</b> ligando: Always → Number → Velocity.",
    sos=[("O fio não aparece","Arraste <b>devagar</b>, de uma bolinha até a outra, e solte em cima da segunda. Rápido demais, o Flowlab só acende a bolinha."),
         ("Liguei na bolinha errada","Arraste o fio para fora e solte no vazio para desfazer; depois refaça."),
         ("Não acho o Velocity","Ele está em <span class=ui>Properties</span>, na coluna da esquerda — não em Components."),
         ("Arrastei o bloco e ele não ficou","Puxe de novo, mais devagar, e solte no meio da área escura.")]),

  dict(n=17, titulo="Escreva o número que faz subir", img="aula3/p15_menos_meio.jpg", clipe="botao_menos.gif",
    corpo="O <span class=ui>Number</span> ainda mostra <b>0</b>, e com zero a lava fica parada.<br><br><b>Aperte e segure</b> um instante em cima do <span class=ui>Number</span> — clique rápido só seleciona o bloco — e abre a janelinha de ajustes.<br><br>No campo <span class=ui>Current value</span>, apague o que estiver lá e escreva <b>0.5</b>. Depois clique <b>uma vez</b> no botão <b>−</b>, à direita do campo: o número vira <b>-0.5</b>. Feche na janelinha no <span class=ui>OK</span>.<br><br>Por que não digitar o traço: o campo <b>engole</b> o sinal de menos quando ele é a primeira coisa que você digita. O botão <b>−</b> tira 1 do valor a cada clique — é por isso que 0.5 vira -0.5.<br><br>E por que negativo: no Flowlab, <b>y para cima é negativo</b>. Com <b>-0.5</b> a lava sobe devagar, e você tem uns <b>16 segundos</b> para subir a escada inteira.",
    ck="O <span class=ui>Number</span>, no meio da mesa, mostra <b>-0.5</b>.",
    sos=[("A janelinha de ajustes não abre","Clique rápido só seleciona o bloco. Aperte e <b>segure</b> um instante antes de soltar."),
         ("Ficou 0.5 em vez de -0.5","Você digitou o traço e ele sumiu. Apague, escreva só <b>0.5</b> e clique uma vez no botão <b>−</b>."),
         ("Ficou -0.5 mas a lava desce","Confira o fio: ele tem de chegar no <span class=ui>y</span> do Velocity, não no <span class=ui>x</span>."),
         ("Cliquei duas vezes no menos","Ficou -1.5. Clique no <b>+</b> uma vez para voltar.")]),

  dict(n=18, titulo="Faça a lava recomeçar o jogo", img="aula3/p16_lava_reinicia.jpg", clipe=None,
    corpo="Ainda na mesa da lava, arraste mais dois blocos para a parte de baixo:<br><br><b>1.</b> Em <span class=ui>Triggers</span>, o <span class=ui>Collision</span>.<br><b>2.</b> Em <span class=ui>Game Flow</span>, o <span class=ui>Restart Game</span>.<br><br>Ligue <span class=ui>hit</span> do Collision até <span class=ui>go</span> do Restart Game.<br><br>Agora o passo que muda tudo: <b>aperte e segure</b> em cima do <span class=ui>Collision</span> para abrir a janelinha. Na lista de cima, onde está escrito <span class=ui>Any Type</span>, clique e escolha <b>Jogador</b>. Feche no <span class=ui>OK</span>.<br><br>Em <span class=ui>Any Type</span> a batida conta com <b>qualquer coisa</b> — e a primeira coisa que a lava encontra subindo é o <b>chão</b>. O jogo recomeçaria sozinho a cada poucos segundos e a fase ficaria impossível, sem nada no editor avisar.<br><br>Saia da mesa no <span class=ui>OK</span> azul e feche o painel do objeto.",
    ck="O bloco <span class=ui>Collision</span> mostra <b>Jogador</b> escrito embaixo dele, e um fio vai dele até o <span class=ui>RestartGame</span>.",
    sos=[("Jogador não aparece na lista","Volte ao passo 6: o campo <span class=ui>Type</span> do boneco precisa estar escrito <b>Jogador</b>. É esse nome que aparece aqui."),
         ("O jogo recomeça sozinho sem eu encostar","A lista ficou em <span class=ui>Any Type</span>. Abra o Collision de novo e escolha <b>Jogador</b>."),
         ("Não acho o Restart Game","Ele está em <span class=ui>Game Flow</span>, na coluna da esquerda.")]),

  dict(n=19, titulo="Ponha a estrela no alto", img="aula3/p19_estrela_pronta.jpg", clipe=None,
    corpo="Clique na casa <b>em cima da ponta direita do degrau mais alto</b> e escolha <span class=ui>Create</span>.<br><br>Em <span class=ui>Name</span>, escreva <b>Estrela</b>. Clique em <span class=ui>edit sprite</span>, pinte de <b>amarelo</b> e feche no <span class=ui>OK</span>.<br><br>Clique em <span class=ui>Behaviors</span> e arraste dois blocos: o <span class=ui>Collision</span> (em <span class=ui>Triggers</span>) e o <span class=ui>Destroyer</span> (em <span class=ui>Components</span>). Ligue <span class=ui>hit</span> até <span class=ui>in</span>.<br><br>E de novo o tipo: <b>aperte e segure</b> em cima do <span class=ui>Collision</span>, e na lista <span class=ui>Any Type</span> escolha <b>Jogador</b>.<br><br>Sem isso, a <b>lava</b> encosta na estrela quando passa por ela e a destrói — o jogo se ganha sozinho antes de você chegar lá, e o que você vê é uma estrela sumindo do nada.",
    ck="A estrela amarela está na ponta de cima da escada, e o <span class=ui>Collision</span> dela mostra <b>Jogador</b>.",
    sos=[("A estrela some sozinha quando jogo","A lista do Collision dela ficou em <span class=ui>Any Type</span>. Abra e escolha <b>Jogador</b>."),
         ("A estrela caiu","Ela não precisa de física nenhuma. Se você marcou <span class=ui>movable</span> nela, desmarque."),
         ("Não acho o Destroyer","Ele está em <span class=ui>Components</span>, na coluna da esquerda.")]),

  dict(n=20, titulo="Jogue: suba antes da lava", img="aula3/p21_jogo.jpg", clipe="jogar.gif",
    corpo="Clique em <span class=ui>Play</span>, na fileira de baixo.<br><br>O jogo abre numa página só dele. <b>Clique uma vez dentro do jogo</b> (para o teclado ir para lá) e jogue: <b>seta para a direita</b> para correr, <b>seta para cima</b> para pular. Segure a direita <b>enquanto</b> pula — parado, o boneco sobe e cai no mesmo lugar.<br><br>Suba os três degraus e ande até a estrela: ela <b>some</b> quando você encosta. Se a lava te alcançar antes, o jogo <b>recomeça</b> e você tenta de novo.<br><br>O endereço desta página é o link do seu jogo: dá para mandar para a sua família tentar.",
    ck="A lava sobe sozinha, o boneco pula entre os degraus, e encostar na estrela faz ela sumir.",
    sos=[("O boneco não anda","Clique uma vez dentro do jogo antes de usar as setas; o teclado precisa estar 'dentro' dele."),
         ("Ele pula parado e não atravessa o vão","Segure a seta da direita <b>junto</b> com o pulo, não uma depois da outra."),
         ("A lava não sobe","Confira duas coisas: o <b>-0.5</b> no <span class=ui>Number</span> (passo 17) e os dois fios (passo 16)."),
         ("A lava sobe mas não me mata","Volte ao passo 15: falta marcar <span class=ui>enable collisions</span>.")]),
 ],
}
